# Jekyll Defaults
title: y.wu in gh
description: yuli wu in github.io
baseurl: "https://yuliwu.github.io/" # the subpath of your site, e.g. /blog
url: "https://yuliwu.github.io"
highlighter: rouge
markdown: kramdown
permalink: /post/:title/
paginate: 5
gems: [jekyll-paginate]
paginate_path: "/page:num"
rss_path: /feed.xml
navigation:
- text: Résumé
  url: /resume/
- text: Archives
  url: /archives/
- text: y|w
  url: /wuyulisite/
- text: About
  url: /about/
  

